### ISSUE TITLE
healer will not build/config

### ISSUE THREAD

**Issue by Altruy** [SunHao-0/healer#34]
i am getting this error when i try to prepare config files
![image](https://user-images.githubusercontent.com/70485527/124365326-a51c5280-dc60-11eb-95ec-52364750efa0.png)
i was trying to prepare the working directory , what files need in the bin folder and desc folder i have these, are these enough?
![image](https://user-images.githubusercontent.com/70485527/124365389-21af3100-dc61-11eb-9d9f-39e7cd480527.png)
![image](https://user-images.githubusercontent.com/70485527/124365446-8d919980-dc61-11eb-8c6b-52054365f3ba.png)

please guide in making working directory

**Comment by SunHao-0** [comment]
Sorry for the late. The code and documentation you use are pretty old. Please read the [latest documentation](https://github.com/SunHao-0/healer) and build the code from the `main` branch. Let me know if there are any other problems.
