### ISSUE TITLE
What is the config of healer?

### ISSUE THREAD

**Issue by selfbypass** [SunHao-0/healer#38]
Hello hao, i want to know how many processes or cpus are configured when healer is executed, like syzkaller's my.cfg?

**Comment by SunHao-0** [comment]
The default configuration is controlled by the default value of command arguments, see [here](https://github.com/SunHao-0/healer/blob/main/healer_fuzzer/src/main.rs#L10). For example, this [line](https://github.com/SunHao-0/healer/blob/main/healer_fuzzer/src/main.rs#L16) means Healer uses 4 jobs by default. More information can be found here [1](https://github.com/SunHao-0/healer/blob/main/healer_fuzzer/src/config.rs#L19), [2](https://github.com/SunHao-0/healer/blob/main/syz_wrapper/src/repro.rs#L27), [3](https://github.com/SunHao-0/healer/blob/main/syz_wrapper/src/report.rs#L17), [4](https://github.com/SunHao-0/healer/blob/main/healer_utils/healer_vm/src/qemu.rs#L24).

**Comment by selfbypass** [comment]
> The default configuration is controlled by the default value of command arguments, see [here](https://github.com/SunHao-0/healer/blob/main/healer_fuzzer/src/main.rs#L10). For example, this [line](https://github.com/SunHao-0/healer/blob/main/healer_fuzzer/src/main.rs#L16) means Healer uses 4 jobs by default. More information can be found here [1](https://github.com/SunHao-0/healer/blob/main/healer_fuzzer/src/config.rs#L19), [2](https://github.com/SunHao-0/healer/blob/main/syz_wrapper/src/repro.rs#L27), [3](https://github.com/SunHao-0/healer/blob/main/syz_wrapper/src/report.rs#L17), [4](https://github.com/SunHao-0/healer/blob/main/healer_utils/healer_vm/src/qemu.rs#L24).

Thanks, it means healer utilizes 4jobs(VMs), every job configured 2cpus? And sorry, i do not find the number of processes configured to per jobs. The 2.2x speed mentioned in your paper is achieved under this default configuration?

**Comment by SunHao-0** [comment]
>  it means healer utilizes 4jobs(VMs), every job configured 2cpus?

Yes, this is the default configuration for fuzzer, if you don't supply any cmd argument.

> ... under this default configuration?

No, this is just default behavior of fuzzer. I think this part has been explained in the paper.

**Comment by SunHao-0** [comment]
This can be closed now. Feel free to open it again if the comments did not resolve your questions.
