### ISSUE TITLE
Dataset from the HEALER paper

### ISSUE THREAD

**Issue by Wayne-Bai** [SunHao-0/healer#41]
Hi @SunHao-0 , I have already read your paper about HEALER. Also. I remember you mentioned that you use a strong_distill.db for Moonshine. Could you share it with us?

**Comment by SunHao-0** [comment]
Hi Weiheng,

Sorry for the late, I noticed your email this morning.  

The `strong_distill.db` was generated by Moonshine with its strong distillation strategy. I think extracting seeds based on your experiment's design and requirements would be more reasonable. You can follow their detailed guidance [here](https://github.com/shankarapailoor/moonshine#run). Besides, the `strong-distill.db` based experiments were conducted a long time ago. It would cost more time to find the old seeds than regenerate them.

**Comment by Wayne-Bai** [comment]
Hi Hao, Thanks for your reply and thanks for the information. But I’m struggling with generating the seed from Moonshine. Could you give me some advice? Are you using wechat? Could I add your wechat that we could talk about more details if you are ok with that? Also, I saw from your website that you are excellent on RUST and looking for some opportunities to pursue a Ph.D career. I could introduce our lab to you since we are going to work on some RUST projects. Looking forward to your reply. Best,Weiheng  From: Hao SunSent: Sunday, February 20, 2022 7:50 PMTo: SunHao-0/healerCc: Weiheng Bai; AuthorSubject: Re: [SunHao-0/healer] Dataset from the HEALER paper (Issue #41) Hi Weiheng,Sorry for the late, I noticed your email this morning.The strong_distill.db was generated by Moonshine with its strong distillation strategy. I think extracting seeds based on your experiment's design and requirements would be more reasonable. You can follow their detailed guidance here. Besides, the strong-distill.db based experiments were conducted a long time ago. It would cost more time to find the old seeds than regenerate them.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Wayne-Bai** [comment]
Hi Hao, By the way, my wechat is 15122191393 (Wayne Bai), if you’d like to add my wechat. Best,Weiheng From: Hao SunSent: Sunday, February 20, 2022 7:50 PMTo: SunHao-0/healerCc: Weiheng Bai; AuthorSubject: Re: [SunHao-0/healer] Dataset from the HEALER paper (Issue #41) Hi Weiheng,Sorry for the late, I noticed your email this morning.The strong_distill.db was generated by Moonshine with its strong distillation strategy. I think extracting seeds based on your experiment's design and requirements would be more reasonable. You can follow their detailed guidance here. Besides, the strong-distill.db based experiments were conducted a long time ago. It would cost more time to find the old seeds than regenerate them.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by SunHao-0** [comment]
This can be closed now. Feel free to reopen it if related issues happened.
